name: telodoy
description: A cross-platform file sharing app using broadcast discovery.
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.5

flutter:
  uses-material-design: true
