name: telodoy
description: A cross-platform file sharing app using broadcast discovery.
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.2.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  open_filex: ^4.0.0
  flutter_webrtc: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
