name: libredrop
description: A cross-platform file sharing app using broadcast discovery.
version: 0.3.0-beta.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.2.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  open_filex: ^4.0.0
  flutter_webrtc: ^1.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
