name: libredrop
description: A cross-platform file sharing app using broadcast discovery.
version: 0.3.0-beta.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.3.2
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  open_filex: ^4.0.0
  flutter_webrtc: ^0.14.2
  receive_sharing_intent: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
